version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"

# covered by GitHub defaults
#   - package-ecosystem: "pip"
#     directory: "/"
#     schedule:
#       interval: "daily"

  - package-ecosystem: "docker"
    directory: "/binder"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/base-notebook"
    schedule:
      interval: "daily"
